// Copyright 2021-2023 ChibiOS HAL team
// SPDX-License-Identifier: Apache-2.0

/*
 * This file was auto-generated by:
 * contrib/chibios/tools/genhalconf.py
 */

#pragma once

#define HAL_USE_I2C            TRUE
#define HAL_USE_SPI            TRUE
//#define HAL_USE_SERIAL         TRUE
#define HAL_USE_USB            TRUE
#define HAL_USE_PWM            TRUE
#define HAL_USE_PAL            TRUE

#include_next "halconf.h"