    name: Build QMK firmware

    on: [push, pull_request]

    jobs:
      build:
        runs-on: ubuntu-latest
        container: ghcr.io/qmk/qmk_cli

        steps:
          - name: Checkout QMK Userspace
            uses: actions/checkout@v4
            with:
              path: userspace

          - name: Clone QMK Firmware
            uses: actions/checkout@v4
            with:
              repository: qmk/qmk_firmware
              path: qmk_firmware

          - name: Setup QMK environment
            run: |
              qmk setup -H qmk_firmware --yes
              qmk config userspace.path=userspace

          - name: Compile firmware
            run: qmk compile -kb crkbd/rev4_1/standard -km default

          - name: List compiled files
            run: |
              ls -la qmk_firmware/
              find . -name "*.uf2"  # Debug: Find all UF2 files
    
          - name: Verify UF2 file exists
            run: |
              if [ ! -f qmk_firmware/*.uf2 ]; then
                echo "Error: No UF2 file found"
                exit 1
              fi

          - name: Upload firmware artifact
            uses: actions/upload-artifact@v4
            with:
              name: qmk-firmware
              path: qmk_firmware/*.uf2 # Adjust path and extension as needed
